### ISSUE TITLE
 new functions string.pack, string.unpack

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.3#1]
Should we try and use Roberto's struct library? It's *almost* compatible

New functions:
  - string.pack
  - string.unpack
  - string.packsize

**Comment by siffiejoe** [comment]
`compat53.lua` now tries to load Robterto's struct library to set `string.pack`, `string.packsize`, and `string.unpack`. At some later point I might try to backport the real Lua 5.3 string packing functions, but that will require actual code changes because we don't have Lua 5.3's buffer API available in Lua 5.1.

**Comment by daurnimator** [comment]
I did send an email to roberto the other day asking him to update struct to the 5.3 api. Sadly he hasn't responded.

**Comment by siffiejoe** [comment]
We now use a backport from Lua 5.3, and it passes a subset of the test suite (large integers are a problem, though).

**Comment by daurnimator** [comment]
cool :)
Roberto said he'd get to it in February :P
