### ISSUE TITLE
Set __name in luaL_newmetatable

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/lua-compat-5.3#13]
In 5.3, lua sets the metatable field `__name` when you use `luaL_newmetatable`

**Comment by siffiejoe** [comment]
I think the real question is: Should we re-implement `luaL_checkudata` to *use* `__name`. On one hand the function is already available on all supported Lua versions and the only change is in an error message. On the other hand I found the more specific error messages useful enough so that I had something like this in my own helper toolkit even before Lua 5.3. If we don't provide an updated `luaL_checkudata`, we probably shouldn't re-implement `luaL_newmetatable` either (although `__name` *is* mentioned in the Lua 5.3 manual).

Opinions?

@daurnimator: What do you need `__name` for?

**Comment by daurnimator** [comment]
> @daurnimator: What do you need __name for?

I have code that does argument checking via `getmetatable(foo).__name`, which works fine on 5.3 but not in 5.1 :)

**Comment by siffiejoe** [comment]
> I have code that does argument checking via getmetatable(foo).__name, which works fine on 5.3 but not in 5.1 :)

How do you handle metatables created without `luaL_newmetatable` (or by third party modules not using Compat-5.3)? Not to mention userdata that have `__metatable` set, or that you might want to allow replacement objects that implement the same interface but with a different metatable name.

**Comment by daurnimator** [comment]
> How do you handle metatables created without luaL_newmetatable (or by third party modules not using Compat-5.3)? Not to mention userdata that have __metatable set, or that you might want to allow replacement objects that implement the same interface but with a different metatable name.

This was internal in a library.

**Comment by daurnimator** [comment]
Added in fb114d8dc6810133ba9e10d75fa9887ee169bf5d.

Thanks!

PS, the implementation is exactly what I would have written! :)
