### ISSUE TITLE
lua_tointegerx accepts non-integers

### ISSUE THREAD

**Issue by RhodiumToad** [keplerproject/lua-compat-5.3#40]
lua_tointegerx only looks for a nonzero result from lua_tointeger or a true result from lua_isnumber (NOT lua_isinteger). This results in it accepting non-integer values and truncating them to integers.

It needs to use the same comparison logic used in lua_isinteger instead.

**Comment by daurnimator** [comment]
Not just `lua_tointegerx`: `lua_tointeger` itself should throw if the value is not integral

**Comment by siffiejoe** [comment]
Fixed for Lua 5.1. Requires some more thought for 5.2.

**Comment by nevkontakte** [comment]
I don't this this change is correct.

Citing Lua [manual](https://www.lua.org/manual/5.3/manual.html#3.4.3):
> The C API also converts both integers to floats and floats to integers, as needed.

The fact that lua_tointeger(x) does return a non-zero value even when lua_isinteger is false seems to be by design.

Could you please revert this change? It has caused a pretty sneaky bug in [FlyWithLua](https://forums.x-plane.org/index.php?/forums/topic/164744-fwl-ng-278-issues-with-draw_string-functions/), which uses LuaJit, when we started using sol2, which has lua-compat-5.3 built in.

**Comment by nevkontakte** [comment]
Sorry my bad. I should've read the document I've linked myself more carefully:
> The conversion from float to integer checks whether the float has an exact representation as an integer (that is, the float has an integral value and it is in the range of integer representation). If it does, that representation is the result. Otherwise, the conversion fails.

Thanks for the quick response.
